# Generated by Django 6.0 on 2025-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='umum', max_length=100),
            preserve_default=False,
        ),
    ]
